import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docPath = join(root, "docs/IOS_CRT_KNOWN_FAILURES.md");
const agents = readFileSync(join(root, "AGENTS.project.md"), "utf8");
const host = readFileSync(join(root, "src/lib/emu/host.ts"), "utf8");
const paint = readFileSync(join(root, "src/lib/emu/ios-paint.ts"), "utf8");
const present = readFileSync(join(root, "src/lib/emu/ios-present.ts"), "utf8");
const gate = readFileSync(join(root, "scripts/crt-fill-gate.mjs"), "utf8");
const docs = readFileSync(join(root, "docs/STATIC-HOSTING.md"), "utf8");

test("known-failures doc exists and lists Tom phone failures 1–10", () => {
  assert.equal(existsSync(docPath), true);
  const doc = readFileSync(docPath, "utf8");
  assert.match(doc, /Read `docs\/IOS_CRT_KNOWN_FAILURES\.md` first/);
  assert.match(doc, /toDataURL|PNG poll/);
  assert.match(doc, /scale\(\)|wrapper/);
  assert.match(doc, /drawImage/);
  assert.match(doc, /false green|false-green/i);
  assert.match(doc, /without Tom/);
  assert.match(doc, /#47/);
  assert.match(doc, /readPixels/);
  assert.match(doc, /14fps|~14fps/);
  assert.match(doc, /8876d8a/);
  assert.match(doc, /### 7\.|#7/);
  assert.match(doc, /6c10228/);
  assert.match(doc, /### 8\.|#8/);
  assert.match(doc, /9c35eb7/);
  assert.match(doc, /unlock/);
  assert.match(doc, /clientWidth/);
  assert.match(doc, /count:0|empty black/i);
  assert.match(doc, /CSS 100% \+ clientWidth/);
  assert.match(doc, /letterbox|384×272 CSS/);
  assert.match(doc, /### 9\.|#9|#50/);
  assert.match(doc, /5a43c67/);
  assert.match(doc, /BPUU8W3r|postage stamp/);
  assert.match(doc, /Plex paint-count ≠ Tom geometry|paint-count ≠ Tom geometry/);
  assert.match(doc, /### 10\.|#10|#51/);
  assert.match(doc, /7d09f7a/);
  assert.match(doc, /2Aufi9H1/);
  assert.match(doc, /zoom-from-default-origin|top-left origin/);
  assert.match(doc, /L on left \+ bottom|L-border|L left\+bottom/);
  assert.match(doc, /Plex `zoom:3` still ≠ Tom geometry|Plex `zoom:3` ≠ Tom/);
  assert.match(doc, /JiffyDOS/);
  assert.match(doc, /#39/);
  assert.match(doc, /build-id|build id/i);
  assert.match(doc, /PETSCII/);
  assert.match(doc, /unit-8|unit 8/i);
  assert.match(doc, /#41/);
  assert.match(doc, /Tom.s phone is the only PASS/);
});

test("project agents and CRT follow-ups point at the known-failures doc", () => {
  assert.match(agents, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
  assert.match(agents, /1–10|1-10/);
  assert.match(agents, /zoom|#51|#50|g64-ios-slot/);
  assert.match(paint, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
  assert.match(host, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
  assert.match(present, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
  assert.match(gate, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
  assert.match(docs, /docs\/IOS_CRT_KNOWN_FAILURES\.md/);
});

test("new CRT path is native 384×272 + centered zoom slot, not failed approaches 1–10", () => {
  const iosFn = host.slice(host.indexOf("function letterboxNativeCss"), host.indexOf("export async function recycleCore"));
  assert.match(iosFn, /letterboxNativeCss/);
  assert.match(iosFn, /ensureIosZoomHost/);
  assert.match(iosFn, /ensureIosZoomSlot/);
  assert.match(iosFn, /applyIosZoomHost/);
  assert.match(iosFn, /applyIosZoomSlot/);
  assert.match(iosFn, /layoutIosCrtHost/);
  assert.match(iosFn, /iosZoomLayout/);
  assert.match(iosFn, /"zoom"/);
  assert.match(iosFn, /width", "384px"/);
  assert.match(iosFn, /height", "272px"/);
  assert.match(iosFn, /flex", "0 0 384px"/);
  assert.match(iosFn, /stripIosPresent/);
  assert.doesNotMatch(iosFn, /fillBezelCss/);
  assert.doesNotMatch(iosFn, /width", "100%"/);
  assert.doesNotMatch(iosFn, /scale\(/);
  assert.doesNotMatch(iosFn, /(?<!un)lockIosClientBox\(canvas/);
  const iosCode = iosFn.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
  assert.doesNotMatch(iosCode, /readPixels/);
  const presentCode = present.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
  assert.doesNotMatch(presentCode, /readPixels/);
  assert.doesNotMatch(presentCode, /drawImage/);
  assert.doesNotMatch(presentCode, /toDataURL/);
  assert.match(paint, /live-webgl/);
  assert.match(paint, /zoom/);
  assert.match(paint, /layoutIosCrtHost/);
  const patched = host.slice(host.indexOf("function preserveWebglBuffer"), host.indexOf("type GuardedGm"));
  assert.match(patched, /width", "384px"/);
  assert.doesNotMatch(patched, /lockIosClientBox\(this,\s*384,\s*272\)/);
});

test("gate never claims PASS and requires centered slot plus native GL CSS", () => {
  assert.match(gate, /Tom's phone is the only PASS/);
  assert.match(gate, /must never claim PASS|never claim PASS/i);
  assert.doesNotMatch(gate, /GATE PASS/);
  assert.match(gate, /Plex paint-count ≠ Tom geometry|paint-count ≠ Tom geometry/);
  assert.match(gate, /letterboxPaintFails/);
  assert.match(gate, /g64-ios-zoom/);
  assert.match(gate, /g64-ios-slot/);
  assert.match(gate, /slotSharesCenter|shares a center/);
  assert.match(gate, /no 2D present canvas covering live GL/);
  assert.match(gate, /GL clientWidth is native 384x272/);
  assert.doesNotMatch(gate, /present canvas revealed after a lit copy/);
  assert.doesNotMatch(gate, /present bitmap stays 384x272/);
  assert.doesNotMatch(gate, /live GL CSS px vs bezel/);
});
