    a.label("waitf")
    a.label("wvs")
    a.lda_abs(0xD012)
    a.emit(CMP_IMM, 252)
    a.emit(BNE)
    a.rel8("wvs")
    a.emit(SEI)
    a.lda_imm(0xFF)
    a.sta_abs(0xDC00)
    a.lda_abs(0xDC00)
    a.emit(AND_IMM, 0x10)
    a.emit(BEQ)
    a.rel8("gotfire")
    a.lda_abs(0xDC01)
    a.emit(CLI)
    a.emit(AND_IMM, 0x10)
    a.emit(BNE)
    a.rel8("waitf")
    a.emit(JMP_ABS)
    a.abs16("gotfire")
    a.label("gotfire")
    a.emit(CLI)